### ISSUE TITLE
剪贴板图片透明参数丢失

### ISSUE THREAD

**Issue by ceastld** [ceastld/QuickerDevelop#1]

**Comment by Darcy-C** [comment]
![R3SFM4UF R9(QWSB$WI~$5A](https://user-images.githubusercontent.com/55233354/141102951-aa1fe73e-e561-4411-b0cd-f8074802e349.jpg)

**Comment by ceastld** [comment]
![~AT@V( {RCJMVKRDP@FK4HI](https://user-images.githubusercontent.com/61349137/141103128-760ac9df-76aa-47e8-a066-d3d1aba11160.jpg)
